# .github/workflows/main.yml
name: Run Twitter Bot

on:
  schedule:
    - cron: '0 22 * * 1'   # JST 7:00
    - cron: '0 2 * * 1 '    # JST 11:00
    - cron: '0 6 * * 1'    # JST 15:00
    - cron: '0 11 * * 1'   # JST 20:00
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      API_KEY_1: ${{ secrets.API_KEY_1 }}
      API_SECRET_KEY_1: ${{ secrets.API_SECRET_KEY_1 }}
      ACCESS_TOKEN_1: ${{ secrets.ACCESS_TOKEN_1 }}
      ACCESS_TOKEN_SECRET_1: ${{ secrets.ACCESS_TOKEN_SECRET_1 }}
      API_KEY_2: ${{ secrets.API_KEY_2 }}
      API_SECRET_KEY_2: ${{ secrets.API_SECRET_KEY_2 }}
      ACCESS_TOKEN_2: ${{ secrets.ACCESS_TOKEN_2 }}
      ACCESS_TOKEN_SECRET_2: ${{ secrets.ACCESS_TOKEN_SECRET_2 }}
      API_KEY_3: ${{ secrets.API_KEY_3 }}
      API_SECRET_KEY_3: ${{ secrets.API_SECRET_KEY_3 }}
      ACCESS_TOKEN_3: ${{ secrets.ACCESS_TOKEN_3 }}
      ACCESS_TOKEN_SECRET_3: ${{ secrets.ACCESS_TOKEN_SECRET_3 }}
      API_KEY_4: ${{ secrets.API_KEY_4 }}
      API_SECRET_KEY_4: ${{ secrets.API_SECRET_KEY_4 }}
      ACCESS_TOKEN_4: ${{ secrets.ACCESS_TOKEN_4 }}
      ACCESS_TOKEN_SECRET_4: ${{ secrets.ACCESS_TOKEN_SECRET_4 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter Bot
        run: python main.py
